### ISSUE TITLE
You have requested a non-existent parameter "setono_sylius_analytics.model.property.class"

### ISSUE THREAD

**Issue by x-wf** [Setono/SyliusAnalyticsPlugin#21]
### Installed
```console
composer require setono/sylius-analytics-plugin
```

### Config
```php
<?php
# config/bundle.php
return [
    ...
    Setono\TagBagBundle\SetonoTagBagBundle::class => ['all' => true],
    Setono\SyliusAnalyticsPlugin\SetonoSyliusAnalyticsPlugin::class => ['all' => true],
    Sylius\Bundle\GridBundle\SyliusGridBundle::class => ['all' => true],
];
```

```yaml
# config/routes/setono_sylius_analytics.yaml
setono_sylius_analytics:
    resource: "@SetonoSyliusAnalyticsPlugin/Resources/config/routing.yaml"
```

```yaml
# config/packages/_sylius.yaml
imports:
   ...
    - { resource: "@SetonoSyliusAnalyticsPlugin/Resources/config/app/config.yaml" }
```

## Symptom
When I execute `php bin/console doctrine:migrations:diff` I get the following error:
```bash
$ php bin/console doctrine:migrations:diff

In ParameterBag.php line 100:
                                                                                               
  You have requested a non-existent parameter "setono_sylius_analytics.model.property.class".  
```
